In [1]:
import os
import ijson
import pandas as pd

# Funkcja do strumieniowego wczytywania danych z pliku JSON
def process_json_file(file_path, output_csv, columns, first_file):
    with open(file_path, 'r', encoding='utf-8') as f:
        rows = []  # Tymczasowe przechowywanie wierszy
        for item in ijson.items(f, 'item'):  # Iteracja po elementach JSON
            row = {key: item.get(key, None) for key in columns}  # Wyciąganie potrzebnych kolumn
            rows.append(row)

            # Zapisuj dane partiami co 1000 wierszy
            if len(rows) >= 1000:
                pd.DataFrame(rows).to_csv(output_csv, mode='w' if first_file else 'a', 
                                          header=first_file, index=False)
                rows = []  # Wyczyść bufor
                first_file = False

        # Zapisz pozostałe dane
        if rows:
            pd.DataFrame(rows).to_csv(output_csv, mode='w' if first_file else 'a', 
                                      header=first_file, index=False)

# Ścieżka do folderu z plikami JSON
folder_path = '/Users/tymoteuszhuba/Desktop/Python/my_projects/JustJoinIT_project/data'
output_csv = 'processed_data.csv'

# Kolumny, które chcesz zachować
columns = ['title', 'marker_icon', 'workplace_type', 'company_name', 'city', 'country_code', 'company_size', 'experience_level', 'remote', 'skills', 'employment_types', 'published_at']

# Przetwarzanie plików w folderze
first_file = True
for file_name in os.listdir(folder_path):
    if file_name.endswith('.json'):
        file_path = os.path.join(folder_path, file_name)
        process_json_file(file_path, output_csv, columns, first_file)
        first_file = False

print(f"Dane zapisane do {output_csv}")

Dane zapisane do processed_data.csv

In [2]:
df = pd.read_csv('/Users/tymoteuszhuba/Desktop/Python/my_projects/JustJoinIT_project/processed_data.csv')
df.head()

,title,marker_icon,workplace_type,company_name,city,country_code,company_size,experience_level,remote,skills,employment_types,published_at
0,SENIOR UI DEVELOPER,game,remote,Dragons Lake,Wrocław,PL,170+,senior,True,"[{'name': 'С++', 'level': 4}]","[{'type': 'permanent', 'salary': None}]",2022-06-07T12:00:00.000Z
1,SENIOR UI DEVELOPER,game,remote,Dragons Lake,Poznań,PL,170+,senior,True,"[{'name': 'С++', 'level': 4}]","[{'type': 'permanent', 'salary': None}]",2022-05-07T12:00:00.000Z
2,Django Full Stack Developer,python,remote,MIM Solutions,Warszawa,PL,30+,senior,True,"[{'name': 'GCloud', 'level': 3}, {'name': 'Jav...","[{'type': 'permanent', 'salary': {'from': 1500...",2022-04-11T17:33:00.000Z
3,Android Developer,mobile,remote,MIM Solutions,Warszawa,PL,30+,senior,True,"[{'name': 'Git', 'level': 3}, {'name': 'Java',...","[{'type': 'b2b', 'salary': {'from': 15000, 'to...",2022-04-11T17:32:00.000Z
4,Product Specialist - Technical Support,support,remote,Kitopi,Kraków,PL,90,junior,True,"[{'name': 'Agile', 'level': 2}, {'name': 'JIRA...","[{'type': 'b2b', 'salary': {'from': 5400, 'to'...",2022-04-11T17:03:00.000Z